### PR TITLE
Typescript types and updates

### PR DESCRIPTION
**Pull request by BendingBender**
- simplify code by not using classes but instead frozen objects
- update to latest Node.js constants + descriptions
- document all exported members
- generate TypeScript types
- only package relevant files to NPM
- add LICENSE file
- add linting and formatting + scripts
- add release automation

### CODE REVIEW

**Comment by panta82** [comment]
Looks amazing, @BendingBender . I can't believe `node_modules` were not gitignored.  😅

I'll add release notes in README.md and release as 2.0, due to the usage of `Object.freeze`.

**Comment by BendingBender** [comment]
The breaking change is not only the `Object.freeze`, it's also the `libuv` and `dlopen` properties are now grouped in separate objects and are not part of `errno` any more.

**Comment by BendingBender** [comment]
And I have another question: not sure if you've seen it, but i introduced a new script in `package.json`, the `release` script. It takes care of tagging, publishing on `npm` and creating a release on Github. What I was missing in this repo are the release tags that are usually made when a package is released on `npm` and this script automates all of the steps.

You can run it in noop mode with `npm run release -- --dry-run` to see what it does. Would you mind using it the next time you make a release? Otherwise, if you don't like it, it would make sense to remove the script, the dev dependency on `release-it` and the readme description of it.

**Comment by panta82** [comment]
> The breaking change is not only the Object.freeze, it's also the libuv and dlopen properties are now grouped in separate objects and are not part of errno any more.

Ah yes, I missed that one. It was obviously a mistake to group them with errno. Realistically, for 99% of use cases, this lib is just a way not to have to type `'ENOENT'` all over the place :).

I'll update README.

> You can run it in noop mode with npm run release -- --dry-run to see what it does. Would you mind using it the next time you make a release? Otherwise, if you don't like it, it would make sense to remove the script, the dev dependency on release-it and the readme description of it.

I missed that one. I quickly scrolled through deps, and thought all you added was activated via pre-publish hooks (generating ts stuff etc.).

I'll definitely use it next time, looks good!

**Comment by panta82** [comment]
Just tried it for patch. It works great.

I think I'll use it for all projects from now on.

**Comment by BendingBender** [comment]
Glad to help.

**Comment by BendingBender** [comment]
> Ah yes, I missed that one. It was obviously a mistake to group them with errno. Realistically, for 99% of use cases, this lib is just a way not to have to type 'ENOENT' all over the place :).

Yeah, was exactly the use case for me.

**Pull request merged**
